### ISSUE TITLE
Velocity Bungee, scoreboard team 

### ISSUE THREAD

**Issue by SmellyOG** [NEZNAMY/TAB-Bridge#18]
https://prnt.sc/SZIDp2p04gX4

java.util.ConcurrentModificationException
[23:27:29 WARN]:        at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
[23:27:29 WARN]:        at TAB-Bridge v2.1.0.jar//me.neznamy.tab.bridge.bukkit.BukkitScoreboard.unregisterTeam(BukkitScoreboard.java:149)
[23:27:29 WARN]:        at TAB-Bridge v2.1.0.jar//me.neznamy.tab.bridge.shared.DataBridge.processPluginMessage(DataBridge.java:175)
[23:27:29 WARN]:        at TAB-Bridge v2.1.0.jar//me.neznamy.tab.bridge.bukkit.BukkitBridge.lambda$onPluginMessageReceived$1(BukkitBridge.java:82)
[23:27:29 WARN]:        at TAB-Bridge v2.1.0.jar//me.neznamy.tab.bridge.shared.TABBridge.lambda$submitTask$0(TABBridge.java:49)
[23:27:29 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[23:27:29 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[23:27:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:27:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:27:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Tanguygab** [comment]
try latest build from actions

**Comment by SmellyOG** [comment]
i'ts latest build

**Comment by Tanguygab** [comment]
from the actions tab or the releases?

**Comment by NEZNAMY** [comment]
It absolutely isn't latest, latest build is called 3.0.0.

**Comment by NEZNAMY** [comment]
Closing as the issue was fixed and plugin will be released soon.
