### ISSUE TITLE
Thread TAB-Bridge Thread failed main thread check: Chunk getEntities call

### ISSUE THREAD

**Issue by johnfriedrich** [NEZNAMY/TAB-Bridge#24]
```Thread TAB-Bridge Thread failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2563) ~[?:?]```

https://pastebin.com/FDCfuAid
On Paper 1.20.1.

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Placeholders#sync-refreshing

**Comment by johnfriedrich** [comment]
Ah, well, thanks
