### ISSUE TITLE
Spam to console

### ISSUE THREAD

**Issue by MrTimotys** [NEZNAMY/TAB-Bridge#26]
I got Tab-Bridge to clear the bungeecord. After connecting to the server I get spam of this type:

Purpur 1.20.1

`[11:16:07] [TAB-Bridge Thread/WARN]: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.bridge.shared.features.TabExpansion.setValue(Object, String, String)" because the return value of "me.neznamy.tab.bridge.shared.TABBridge.getExpansion()" is null
[11:16:07] [TAB-Bridge Thread/WARN]: 	at TAB-Bridge v3.1.4.jar//me.neznamy.tab.bridge.shared.DataBridge.processPluginMessage(DataBridge.java:130)
[11:16:07] [TAB-Bridge Thread/WARN]: 	at TAB-Bridge v3.1.4.jar//me.neznamy.tab.bridge.bukkit.BukkitBridge.lambda$onPluginMessageReceived$1(BukkitBridge.java:90)
[11:16:07] [TAB-Bridge Thread/WARN]: 	at TAB-Bridge v3.1.4.jar//me.neznamy.tab.bridge.shared.TABBridge.lambda$submitTask$0(TABBridge.java:51)
[11:16:07] [TAB-Bridge Thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[11:16:07] [TAB-Bridge Thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[11:16:07] [TAB-Bridge Thread/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[11:16:07] [TAB-Bridge Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:16:07] [TAB-Bridge Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:16:07] [TAB-Bridge Thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by NEZNAMY** [comment]
TAB version? Do you have multiple proxies?

**Comment by MrTimotys** [comment]
TAB.v4.0.4
No, I only have one proxy server running the tab.

**Comment by NEZNAMY** [comment]
Try restarting the server if it continues. Did you get any errors before that?

**Comment by MrTimotys** [comment]
It's a completely new installation - no modifications

the server has been restarted x times

**Comment by MrTimotys** [comment]
Isn't it because there is no placeholderapi on the server yet?

**Comment by MrTimotys** [comment]
Looks like it stopped after adding PAPI, thank you very much.

**Comment by NEZNAMY** [comment]
Apparently that was it. I will fix it.
