### ISSUE TITLE
Generating exceptions on hub server

### ISSUE THREAD

**Issue by Wolvend** [NEZNAMY/TAB-Bridge#4]
[02:11:53 INFO]: UUID of player *flamSword569 is 00000000-0000-0000-0009-01fed67666e2
[02:11:53 INFO]: [floodgate] Floodgate player logged in as *flamSword569 joined (UUID: 00000000-0000-0000-0009-01fed67666e2)
[02:11:53 WARN]: [TAB-Bridge] Plugin TAB-Bridge v2.0.0 generated an exception while executing task 21328
java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.bridge.bukkit.features.unlimitedtags.ArmorStandManager.getArmorStand(String)" because the return value of "me.neznamy.tab.bridge.bukkit.features.unlimitedtags.BridgeNameTagX.getArmorStandManager(me.neznamy.tab.bridge.bukkit.BridgePlayer)" is null
        at me.neznamy.tab.bridge.bukkit.features.unlimitedtags.BridgeNameTagX.readMessage(BridgeNameTagX.java:218) ~[TAB-Bridge-2.0.0.jar:?]
        at me.neznamy.tab.bridge.bukkit.DataBridge.processPluginMessage(DataBridge.java:126) ~[TAB-Bridge-2.0.0.jar:?]
        at me.neznamy.tab.bridge.bukkit.DataBridge.lambda$processPluginMessage$4(DataBridge.java:69) ~[TAB-Bridge-2.0.0.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:11:53 INFO]:  [Trusted] *flamSword569 joined the game

**Comment by Wolvend** [comment]
We are using geyser/floodgate to allow bedrock players to connect

**Comment by NEZNAMY** [comment]
Update to 2.0.1
