### ISSUE TITLE
Bedrock Players - Console Error On Join

### ISSUE THREAD

**Issue by tdherring** [NEZNAMY/TAB-Bridge#6]
On a **bedrock** player's first join after server restart (we are using geyser/floodgate), the following is logged on our backend servers when using unlimited nameplates:

```
[12:13:17 WARN]: [TAB-Bridge] Plugin TAB-Bridge v2.0.1 generated an exception while executing task 7779
java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.bridge.bukkit.features.unlimitedtags.ArmorStandManager.getArmorStand(String)" because the return value of "me.neznamy.tab.bridge.bukkit.features.unlimitedtags.BridgeNameTagX.getArmorStandManager(me.neznamy.tab.bridge.bukkit.BridgePlayer)" is null
        at me.neznamy.tab.bridge.bukkit.features.unlimitedtags.BridgeNameTagX.readMessage(BridgeNameTagX.java:218) ~[TAB-Bridge-2.0.1(1).jar:?]
        at me.neznamy.tab.bridge.bukkit.DataBridge.processPluginMessage(DataBridge.java:136) ~[TAB-Bridge-2.0.1(1).jar:?]
        at me.neznamy.tab.bridge.bukkit.DataBridge.lambda$processPluginMessage$4(DataBridge.java:69) ~[TAB-Bridge-2.0.1(1).jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Subsequently, placeholders in the nametags are not populated. We have to execute `/btab reload` for them to display correctly. The tablist is seemingly not affected by this issue. Java players are not affected.

If you require any further info please let me know!

Thanks

**Comment by NEZNAMY** [comment]
Try latest build from actions.

**Comment by tdherring** [comment]
That seems to have fixed it, thank you!
